cora:
  n_clusters: 7
  encoder_channels: 512
  hidden_channels: 256
  decoder_channels: 64
  encoder_layers: 2
  attribute_decoder_layers: 2
  structure_decoder_layer: 2
  encoder_dropout: 0.4
  attribute_decoder_dropout: 0.4
  structure_decoder_dropout: 0.4
  m: 0.999
  t: 0.1
  K: 2
  temperature: 1
  p: 0.7
  epoch: 1000
  cluster_updating: 20
  lr: 1e-3
  cos: True
  layer: 'gcn'
  bn: 'none'
  encoder_activation: 'elu' 

citeseer:
  encoder_channels: 512
  hidden_channels: 256
  decoder_channels: 64
  encoder_layers: 2
  attribute_decoder_layers: 2
  structure_decoder_layer: 2
  encoder_dropout: 0.4
  attribute_decoder_dropout: 0.4
  structure_decoder_dropout: 0.4
  m: 0.999
  t: 0.1
  K: 2
  temperature: 1
  p: 0.7
  epoch: 1000
  cluster_updating: 20
  lr: 1e-3
  cos: True
  layer: 'gcn'
  bn: 'none'
  encoder_activation: 'elu' 
  
pubmed:
  encoder_channels: 512
  hidden_channels: 256
  decoder_channels: 64
  encoder_layers: 2
  attribute_decoder_layers: 2
  structure_decoder_layer: 2
  encoder_dropout: 0.4
  attribute_decoder_dropout: 0.4
  structure_decoder_dropout: 0.4
  m: 0.999
  t: 0.1
  K: 2
  temperature: 1
  p: 0.7
  epoch: 400
  cluster_updating: 20
  lr: 1e-3
  cos: True
  layer: 'gcn'
  bn: 'none'
  encoder_activation: 'elu'